// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ResponseData {
    "status": string;
    "data": any;
    "msg": string;

    /** Creates a new ResponseData instance. */
    constructor($$source: Partial<ResponseData> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = null;
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponseData instance from a string or object.
     */
    static createFrom($$source: any = {}): ResponseData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResponseData($$parsedSource as Partial<ResponseData>);
    }
}
